spring.application.name=organisador
server.port=8080
# ===============================
# CONEXION A LA BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/organisador_habitos
spring.datasource.username=postgres
spring.datasource.password=jair
spring.datasource.driver-class-name=org.postgresql.Driver


# Muestra en la consola las consultas SQL que Spring ejecuta por detras
spring.jpa.show-sql=true

# Da un formato mas legible al SQL en la consola
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=validate
